#!/usr/bin/env python

import sys
sys.path.append ('googleplay_api')

from googleplay import GooglePlayAPI, LoginError

token = open('token.dat', 'r').read()
api = GooglePlayAPI(androidId = "3d716411bf8bc802", lang = "en_US")
api.login(None, None, token)

print(str(api.search ("aa", nb_results=200).doc))
