#!/usr/bin/env python

import sys
sys.path.append ('googleplay_api')
from googleplay import GooglePlayAPI, LoginError

class GPCrawl:

    def __init__(self, tokenfile, androidid, lang):
        token = open(tokenfile, 'r').read()
        self.api = GooglePlayAPI(androidId = androidid, lang = lang)
        self.api.login(None, None, token)

gpc = GPCrawl (tokenfile = 'token.dat', androidid = '3d716411bf8bc802', lang = 'en_us')
print(str(gpc.api.search ("aa", nb_results=200).doc))
